services:
  app:
    build:
      context: ./app
    environment:
      - DATABASE_URL=mysql+pymysql://devuser:D3v_u53r#@mysql/HOTEL
      - SECRET_KEY=DASHAUTO
    expose:
      - 7000
    volumes:
      - ./app:/app
    depends_on:
      - mysql

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app

  platform:
    image: php:apache
    volumes:
      - ./platform:/var/www/html
    ports:
      - "8080:80"

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=HOTEL
      - MYSQL_USER=devuser
      - MYSQL_PASSWORD=D3v_u53r#
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
